const jobs = [
  {
    Title: "Seasoned Senior python Developer (fresher",
    Company: "XYZ Solution Pvt Ltd",
    Experience: "0 - 1 yrs",
    Salary: "RS: 1 lak to 1.5 lak .p a.",
    Location: "Lahore",
    Skills: "java,python,HTM,CSS,.Net",
    Description: "This job only those who live in lahore that.",
  },
  {
    Title: "Junior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Junior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Junior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Junior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
  {
    Title: "Senior Java Developer",
    Company: "ABC Tech Solutions",
    Experience: "1 - 2 yrs",
    Salary: "RS: 80000 to 100000 per month",
    Location: "Karachi",
    Skills: "Java,Spring,SQL",
    Description: "Exciting opportunity for Java developers in Karachi.",
  },
];
export default jobs;
